services:
   postgres:
      image: postgres
      container_name: postresql
      environment:
         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ports:
         - '5432:5432'
      volumes:
         - postgres_data:/var/lib/postgresql/data
      restart: always
   pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin-container
      environment:
         PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
         PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      ports:
         - '5050:80'
      depends_on:
         - postgres

volumes:
   postgres_data:
